import { BankQuestionTemplate } from '../types';

export interface ConcreteGeometryQuestion {
  prompt: string;
  options: { key: 'A' | 'B' | 'C' | 'D'; text: string }[];
  correctOption: 'A' | 'B' | 'C' | 'D';
  solutionExplanation: string;
  cognitiveLevel: 'nhanBiet' | 'thongHieu' | 'vanDung' | 'vanDungCao';
  learningObjective: string;
  topicKeywords: string[];
  lesson?: string;
  chapter?: string;
}

// ============================================================================
// HÌNH HỌC KHỐI 9 (Hệ thức lượng, Tỉ số lượng giác, Đường tròn, Tứ giác nội tiếp)
// ============================================================================
export const GRADE_9_GEOMETRY_QUESTIONS: ConcreteGeometryQuestion[] = [
  // --- NHẬN BIẾT (9 câu) ---
  {
    prompt: 'Cho tam giác $ABC$ vuông tại $A$, đường cao $AH$. Hệ thức nào sau đây là đúng?',
    options: [
      { key: 'A', text: '$AH^2 = BH \\cdot CH$' },
      { key: 'B', text: '$AH^2 = AB \\cdot AC$' },
      { key: 'C', text: '$AB^2 = BH \\cdot CH$' },
      { key: 'D', text: '$AC^2 = BH \\cdot BC$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trong tam giác vuông, bình phương đường cao ứng với cạnh huyền bằng tích hai hình chiếu của hai cạnh góc vuông trên cạnh huyền: $AH^2 = BH \\cdot CH$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết các hệ thức lượng về cạnh và đường cao trong tam giác vuông.',
    topicKeywords: ['hệ thức lượng', 'tam giác vuông', 'đường cao', 'hình học'],
    chapter: 'Hình học',
    lesson: 'Hệ thức lượng trong tam giác vuông',
  },
  {
    prompt: 'Cho tam giác $ABC$ vuông tại $A$ có góc nhọn $B$. Tỉ số lượng giác $\\sin B$ bằng:',
    options: [
      { key: 'A', text: '$\\frac{AC}{BC}$' },
      { key: 'B', text: '$\\frac{AB}{BC}$' },
      { key: 'C', text: '$\\frac{AC}{AB}$' },
      { key: 'D', text: '$\\frac{AB}{AC}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trong tam giác vuông: Sin đi học = cạnh đối / cạnh huyền $\\Rightarrow \\sin B = \\frac{AC}{BC}$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định nghĩa tỉ số lượng giác sin của góc nhọn.',
    topicKeywords: ['tỉ số lượng giác', 'sin', 'tam giác vuông'],
    chapter: 'Hình học',
    lesson: 'Tỉ số lượng giác của góc nhọn',
  },
  {
    prompt: 'Cho tam giác $ABC$ vuông tại $A$. Tỉ số lượng giác $\\cos B$ được tính theo công thức nào?',
    options: [
      { key: 'A', text: '$\\frac{AB}{BC}$' },
      { key: 'B', text: '$\\frac{AC}{BC}$' },
      { key: 'C', text: '$\\frac{AB}{AC}$' },
      { key: 'D', text: '$\\frac{AC}{AB}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trong tam giác vuông: Cos khóc hoài = cạnh kề / cạnh huyền $\\Rightarrow \\cos B = \\frac{AB}{BC}$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định nghĩa tỉ số lượng giác cos của góc nhọn.',
    topicKeywords: ['tỉ số lượng giác', 'cos', 'tam giác vuông'],
    chapter: 'Hình học',
    lesson: 'Tỉ số lượng giác của góc nhọn',
  },
  {
    prompt: 'Trong các hệ thức lượng trong tam giác vuông, khẳng định nào sau đây SAI (với $a$ là cạnh huyền, $b, c$ là hai cạnh góc vuông, $h$ là đường cao)?',
    options: [
      { key: 'A', text: '$b \\cdot c = a \\cdot h^2$' },
      { key: 'B', text: '$b^2 = a \\cdot b\'$' },
      { key: 'C', text: '$c^2 = a \\cdot c\'$' },
      { key: 'D', text: '$\\frac{1}{h^2} = \\frac{1}{b^2} + \\frac{1}{c^2}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Hệ thức đúng là $b \\cdot c = a \\cdot h$, do đó công thức $b \\cdot c = a \\cdot h^2$ là sai.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết các hệ thức lượng cơ bản trong tam giác vuông.',
    topicKeywords: ['hệ thức lượng', 'cạnh huyền', 'đường cao'],
    chapter: 'Hình học',
    lesson: 'Hệ thức lượng trong tam giác vuông',
  },
  {
    prompt: 'Số đo của góc nội tiếp chắn nửa đường tròn luôn bằng:',
    options: [
      { key: 'A', text: '$90^\\circ$' },
      { key: 'B', text: '$180^\\circ$' },
      { key: 'C', text: '$60^\\circ$' },
      { key: 'D', text: '$45^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định lý: Góc nội tiếp chắn nửa đường tròn là góc vuông ($90^\\circ$).',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết tính chất của góc nội tiếp chắn nửa đường tròn.',
    topicKeywords: ['góc nội tiếp', 'nửa đường tròn', 'đường tròn'],
    chapter: 'Hình học',
    lesson: 'Góc nội tiếp',
  },
  {
    prompt: 'Một đường thẳng $d$ và đường tròn $(O; R)$ tiếp xúc nhau khi và chỉ khi khoảng cách $d(O, d)$ từ tâm $O$ đến $d$ thỏa mãn:',
    options: [
      { key: 'A', text: '$d(O, d) = R$' },
      { key: 'B', text: '$d(O, d) < R$' },
      { key: 'C', text: '$d(O, d) > R$' },
      { key: 'D', text: '$d(O, d) = 2R$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Đường thẳng tiếp xúc với đường tròn khi và chỉ khi khoảng cách từ tâm đến đường thẳng bằng đúng bán kính ($d = R$).',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết vị trí tương đối của đường thẳng và đường tròn.',
    topicKeywords: ['tiếp tuyến', 'đường thẳng', 'đường tròn', 'vị trí tương đối'],
    chapter: 'Hình học',
    lesson: 'Vị trí tương đối của đường thẳng và đường tròn',
  },
  {
    prompt: 'Khẳng định nào sau đây là ĐÚNG về tứ giác nội tiếp đường tròn?',
    options: [
      { key: 'A', text: 'Tổng số đo hai góc đối diện luôn bằng $180^\\circ$' },
      { key: 'B', text: 'Tổng số đo hai góc đối diện luôn bằng $90^\\circ$' },
      { key: 'C', text: 'Hai góc đối diện luôn bằng nhau' },
      { key: 'D', text: 'Bốn góc của tứ giác luôn bằng nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tính chất: Trong một tứ giác nội tiếp, tổng số đo hai góc đối diện luôn bằng $180^\\circ$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết tính chất số đo các góc của tứ giác nội tiếp.',
    topicKeywords: ['tứ giác nội tiếp', 'góc đối diện', 'đường tròn'],
    chapter: 'Hình học',
    lesson: 'Tứ giác nội tiếp',
  },
  {
    prompt: 'Góc ở tâm là góc có:',
    options: [
      { key: 'A', text: 'Đỉnh trùng với tâm của đường tròn' },
      { key: 'B', text: 'Đỉnh nằm trên đường tròn' },
      { key: 'C', text: 'Hai cạnh tiếp xúc với đường tròn' },
      { key: 'D', text: 'Đỉnh nằm bên ngoài đường tròn' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định nghĩa: Góc ở tâm là góc có đỉnh trùng với tâm của đường tròn.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định nghĩa góc ở tâm.',
    topicKeywords: ['góc ở tâm', 'đường tròn', 'tâm'],
    chapter: 'Hình học',
    lesson: 'Góc ở tâm, số đo cung',
  },

  // --- THÔNG HIỂU (8 câu) ---
  {
    prompt: 'Cho tam giác $ABC$ vuông tại $A$ có $AB = 6\\text{ cm}, AC = 8\\text{ cm}$. Giá trị của $\\sin B$ bằng:',
    options: [
      { key: 'A', text: '$\\frac{4}{5}$' },
      { key: 'B', text: '$\\frac{3}{5}$' },
      { key: 'C', text: '$\\frac{4}{3}$' },
      { key: 'D', text: '$\\frac{3}{4}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Độ dài cạnh huyền $BC = \\sqrt{6^2 + 8^2} = 10\\text{ cm}$. Tỉ số $\\sin B = \\frac{AC}{BC} = \\frac{8}{10} = \\frac{4}{5}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính được tỉ số lượng giác của góc nhọn từ độ dài các cạnh.',
    topicKeywords: ['tỉ số lượng giác', 'sin', 'tam giác vuông', 'pythagore'],
    chapter: 'Hình học',
    lesson: 'Tỉ số lượng giác của góc nhọn',
  },
  {
    prompt: 'Cho tam giác $ABC$ vuông tại $A$, đường cao $AH$. Biết $BH = 4\\text{ cm}, CH = 9\\text{ cm}$. Độ dài đường cao $AH$ bằng:',
    options: [
      { key: 'A', text: '$6\\text{ cm}$' },
      { key: 'B', text: '$36\\text{ cm}$' },
      { key: 'C', text: '$13\\text{ cm}$' },
      { key: 'D', text: '$6{,}5\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Áp dụng hệ thức $AH^2 = BH \\cdot CH = 4 \\cdot 9 = 36 \\Rightarrow AH = \\sqrt{36} = 6\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính độ dài đường cao ứng với cạnh huyền.',
    topicKeywords: ['hệ thức lượng', 'đường cao', 'hình chiếu'],
    chapter: 'Hình học',
    lesson: 'Hệ thức lượng trong tam giác vuông',
  },
  {
    prompt: 'Cho góc nhọn $\\alpha$. Biết $\\sin \\alpha = 0{,}6$. Giá trị của $\\cos \\alpha$ bằng:',
    options: [
      { key: 'A', text: '$0{,}8$' },
      { key: 'B', text: '$0{,}4$' },
      { key: 'C', text: '$0{,}64$' },
      { key: 'D', text: '$0{,}36$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Ta có $\\sin^2 \\alpha + \\cos^2 \\alpha = 1 \\Rightarrow \\cos^2 \\alpha = 1 - 0{,}6^2 = 0{,}64 \\Rightarrow \\cos \\alpha = 0{,}8$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Vận dụng hệ thức giữa các tỉ số lượng giác cùng một góc nhọn.',
    topicKeywords: ['hệ thức lượng giác', 'sin', 'cos'],
    chapter: 'Hình học',
    lesson: 'Tỉ số lượng giác của góc nhọn',
  },
  {
    prompt: 'Cho đường tròn $(O; 5\\text{ cm})$ và một dây cung $AB = 8\\text{ cm}$. Khoảng cách từ tâm $O$ đến dây $AB$ bằng:',
    options: [
      { key: 'A', text: '$3\\text{ cm}$' },
      { key: 'B', text: '$4\\text{ cm}$' },
      { key: 'C', text: '$6\\text{ cm}$' },
      { key: 'D', text: '$\\sqrt{41}\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Gọi $H$ là trung điểm của dây $AB \\Rightarrow OH \\perp AB$ và $AH = 4\\text{ cm}$. Theo định lý Pythagore: $OH = \\sqrt{R^2 - AH^2} = \\sqrt{5^2 - 4^2} = 3\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính khoảng cách từ tâm đến dây cung của đường tròn.',
    topicKeywords: ['dây cung', 'đường kính', 'khoảng cách từ tâm'],
    chapter: 'Hình học',
    lesson: 'Đường kính và dây của đường tròn',
  },
  {
    prompt: 'Cho tứ giác $ABCD$ nội tiếp đường tròn $(O)$, biết $\\widehat{A} = 75^\\circ$. Số đo của góc đối diện $\\widehat{C}$ bằng:',
    options: [
      { key: 'A', text: '$105^\\circ$' },
      { key: 'B', text: '$75^\\circ$' },
      { key: 'C', text: '$15^\\circ$' },
      { key: 'D', text: '$115^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trong tứ giác nội tiếp, tổng hai góc đối bằng $180^\\circ$: $\\widehat{C} = 180^\\circ - \\widehat{A} = 180^\\circ - 75^\\circ = 105^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính số đo góc của tứ giác nội tiếp.',
    topicKeywords: ['tứ giác nội tiếp', 'góc đối', 'số đo góc'],
    chapter: 'Hình học',
    lesson: 'Tứ giác nội tiếp',
  },
  {
    prompt: 'Cho đường tròn $(O)$ có góc ở tâm $\\widehat{AOB} = 80^\\circ$. Số đo của góc nội tiếp $\\widehat{ACB}$ cùng chắn cung $AB$ là:',
    options: [
      { key: 'A', text: '$40^\\circ$' },
      { key: 'B', text: '$80^\\circ$' },
      { key: 'C', text: '$160^\\circ$' },
      { key: 'D', text: '$20^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Số đo góc nội tiếp bằng nửa số đo góc ở tâm cùng chắn một cung: $\\widehat{ACB} = \\frac{1}{2} \\widehat{AOB} = \\frac{80^\\circ}{2} = 40^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Hiểu mối liên hệ giữa góc nội tiếp và góc ở tâm cùng chắn một cung.',
    topicKeywords: ['góc ở tâm', 'góc nội tiếp', 'cung'],
    chapter: 'Hình học',
    lesson: 'Góc nội tiếp',
  },
  {
    prompt: 'Tam giác $ABC$ vuông tại $A$ có cạnh huyền $BC = 12\\text{ cm}$ và góc $\\widehat{B} = 30^\\circ$. Độ dài cạnh đối diện góc $30^\\circ$ ($AC$) là:',
    options: [
      { key: 'A', text: '$6\\text{ cm}$' },
      { key: 'B', text: '$6\\sqrt{3}\\text{ cm}$' },
      { key: 'C', text: '$4\\text{ cm}$' },
      { key: 'D', text: '$12\\sqrt{3}\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trong tam giác vuông, cạnh đối diện với góc $30^\\circ$ bằng nửa cạnh huyền: $AC = BC \\cdot \\sin 30^\\circ = 12 \\cdot \\frac{1}{2} = 6\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính cạnh tam giác vuông bằng tỉ số lượng giác.',
    topicKeywords: ['tam giác vuông', 'tỉ số lượng giác', 'góc 30 độ'],
    chapter: 'Hình học',
    lesson: 'Tỉ số lượng giác của góc nhọn',
  },

  // --- VẬN DỤNG (5 câu) ---
  {
    prompt: 'Một cái thang dài $4\\text{ m}$ dựa vào một bức tường tạo với mặt đất một góc $60^\\circ$. Chiều cao từ chân tường lên đỉnh thang chạm tường bằng:',
    options: [
      { key: 'A', text: '$2\\sqrt{3}\\text{ m}$' },
      { key: 'B', text: '$2\\text{ m}$' },
      { key: 'C', text: '$4\\sqrt{3}\\text{ m}$' },
      { key: 'D', text: '$3\\sqrt{2}\\text{ m}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Chiều cao chạm tường $h = 4 \\cdot \\sin 60^\\circ = 4 \\cdot \\frac{\\sqrt{3}}{2} = 2\\sqrt{3}\\text{ m}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Ứng dụng tỉ số lượng giác vào bài toán thực tế.',
    topicKeywords: ['ứng dụng thực tế', 'thang dựa tường', 'sin', 'lượng giác'],
    chapter: 'Hình học',
    lesson: 'Ứng dụng thực tế tỉ số lượng giác',
  },
  {
    prompt: 'Một người đứng cách chân ngọn hải đăng $40\\text{ m}$ nhìn lên đỉnh hải đăng với góc nâng $45^\\circ$. Biết mắt người đó cách mặt đất $1{,}6\\text{ m}$. Chiều cao của ngọn hải đăng là:',
    options: [
      { key: 'A', text: '$41{,}6\\text{ m}$' },
      { key: 'B', text: '$40\\text{ m}$' },
      { key: 'C', text: '$38{,}4\\text{ m}$' },
      { key: 'D', text: '$45{,}6\\text{ m}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Khoảng cách từ mắt đến đỉnh ngang bằng $40 \\cdot \\tan 45^\\circ = 40\\text{ m}$. Chiều cao hải đăng là $40 + 1{,}6 = 41{,}6\\text{ m}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Giải bài toán thực tế tính chiều cao bằng góc nâng.',
    topicKeywords: ['ứng dụng thực tế', 'góc nâng', 'hải đăng', 'tan'],
    chapter: 'Hình học',
    lesson: 'Ứng dụng thực tế tỉ số lượng giác',
  },
  {
    prompt: 'Cho hai tiếp tuyến $MA$ và $MB$ của đường tròn $(O; R)$ cắt nhau tại điểm $M$. Biết góc $\\widehat{AMB} = 60^\\circ$. Số đo góc ở tâm $\\widehat{AOB}$ là:',
    options: [
      { key: 'A', text: '$120^\\circ$' },
      { key: 'B', text: '$60^\\circ$' },
      { key: 'C', text: '$90^\\circ$' },
      { key: 'D', text: '$150^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tứ giác $MAOB$ có hai góc vuông $\\widehat{MAO} = \\widehat{MBO} = 90^\\circ$, suy ra $\\widehat{AOB} = 180^\\circ - 60^\\circ = 120^\\circ$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Vận dụng tính chất hai tiếp tuyến cắt nhau.',
    topicKeywords: ['tiếp tuyến cắt nhau', 'góc ở tâm', 'đường tròn'],
    chapter: 'Hình học',
    lesson: 'Tính chất hai tiếp tuyến cắt nhau',
  },
  {
    prompt: 'Diện tích hình quạt tròn bán kính $R = 6\\text{ cm}$ ứng với cung có số đo $60^\\circ$ bằng:',
    options: [
      { key: 'A', text: '$6\\pi\\text{ cm}^2$' },
      { key: 'B', text: '$12\\pi\\text{ cm}^2$' },
      { key: 'C', text: '$36\\pi\\text{ cm}^2$' },
      { key: 'D', text: '$3\\pi\\text{ cm}^2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Công thức diện tích quạt tròn: $S = \\frac{\\pi R^2 n}{360} = \\frac{\\pi \\cdot 6^2 \\cdot 60}{360} = 6\\pi\\text{ cm}^2$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Vận dụng công thức tính diện tích hình quạt tròn.',
    topicKeywords: ['hình quạt tròn', 'diện tích', 'cung tròn'],
    chapter: 'Hình học',
    lesson: 'Hình quạt tròn',
  },
];

// ============================================================================
// HÌNH HỌC KHỐI 8 (Tứ giác, Định lý Thalès, Tam giác đồng dạng, Hình chóp đều)
// ============================================================================
export const GRADE_8_GEOMETRY_QUESTIONS: ConcreteGeometryQuestion[] = [
  // --- NHẬN BIẾT (9 câu) ---
  {
    prompt: 'Tổng các góc trong một tứ giác lồi luôn bằng:',
    options: [
      { key: 'A', text: '$360^\\circ$' },
      { key: 'B', text: '$180^\\circ$' },
      { key: 'C', text: '$270^\\circ$' },
      { key: 'D', text: '$540^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định lý: Tổng số đo bốn góc của một tứ giác lồi luôn bằng $360^\\circ$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định lý tổng các góc trong một tứ giác.',
    topicKeywords: ['tứ giác', 'tổng các góc', 'hình học'],
    chapter: 'Hình học',
    lesson: 'Tứ giác',
  },
  {
    prompt: 'Hình thang cân là hình thang có:',
    options: [
      { key: 'A', text: 'Hai góc kề một đáy bằng nhau' },
      { key: 'B', text: 'Hai cạnh bên song song' },
      { key: 'C', text: 'Hai đáy bằng nhau' },
      { key: 'D', text: 'Hai góc đối bằng nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định nghĩa: Hình thang cân là hình thang có hai góc kề một đáy bằng nhau (hoặc hai đường chéo bằng nhau).',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định nghĩa và tính chất hình thang cân.',
    topicKeywords: ['hình thang cân', 'góc kề đáy', 'hình thang'],
    chapter: 'Hình học',
    lesson: 'Hình thang cân',
  },
  {
    prompt: 'Hình bình hành có hai đường chéo bằng nhau là hình gì?',
    options: [
      { key: 'A', text: 'Hình chữ nhật' },
      { key: 'B', text: 'Hình thoi' },
      { key: 'C', text: 'Hình vuông' },
      { key: 'D', text: 'Hình thang vuông' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Dấu hiệu nhận biết: Hình bình hành có hai đường chéo bằng nhau là hình chữ nhật.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết dấu hiệu hình chữ nhật từ hình bình hành.',
    topicKeywords: ['hình bình hành', 'hình chữ nhật', 'đường chéo'],
    chapter: 'Hình học',
    lesson: 'Hình chữ nhật',
  },
  {
    prompt: 'Hình thoi có một góc vuông là hình gì?',
    options: [
      { key: 'A', text: 'Hình vuông' },
      { key: 'B', text: 'Hình chữ nhật' },
      { key: 'C', text: 'Hình bình hành' },
      { key: 'D', text: 'Hình thang cân' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Dấu hiệu nhận biết: Hình thoi có một góc vuông là hình vuông.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết dấu hiệu hình vuông từ hình thoi.',
    topicKeywords: ['hình thoi', 'hình vuông', 'góc vuông'],
    chapter: 'Hình học',
    lesson: 'Hình vuông',
  },
  {
    prompt: 'Cho tam giác $ABC$, đường thẳng $d // BC$ cắt $AB$ tại $D$ và $AC$ tại $E$. Hệ thức nào sau đây là ĐÚNG theo định lý Thalès?',
    options: [
      { key: 'A', text: '$\\frac{AD}{AB} = \\frac{AE}{AC}$' },
      { key: 'B', text: '$\\frac{AD}{AC} = \\frac{AE}{AB}$' },
      { key: 'C', text: '$\\frac{AD}{DB} = \\frac{EC}{AE}$' },
      { key: 'D', text: '$\\frac{AD}{AE} = \\frac{AC}{AB}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Theo định lý Thalès: Đường thẳng song song với một cạnh của tam giác định ra trên hai cạnh kia những đoạn thẳng tương ứng tỉ lệ: $\\frac{AD}{AB} = \\frac{AE}{AC}$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định lý Thalès trong tam giác.',
    topicKeywords: ['định lý thalès', 'tỉ lệ', 'song song'],
    chapter: 'Hình học',
    lesson: 'Định lý Thalès trong tam giác',
  },
  {
    prompt: 'Hình chóp tam giác đều có mặt đáy là:',
    options: [
      { key: 'A', text: 'Tam giác đều' },
      { key: 'B', text: 'Tam giác vuông' },
      { key: 'C', text: 'Tam giác cân' },
      { key: 'D', text: 'Tứ giác đều' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định nghĩa: Hình chóp tam giác đều có đáy là tam giác đều và các mặt bên là các tam giác cân bằng nhau.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết đặc điểm hình học của hình chóp tam giác đều.',
    topicKeywords: ['hình chóp tam giác đều', 'mặt đáy', 'tam giác đều'],
    chapter: 'Hình học',
    lesson: 'Hình chóp tam giác đều',
  },
  {
    prompt: 'Hình chóp tứ giác đều có mặt đáy là hình gì?',
    options: [
      { key: 'A', text: 'Hình vuông' },
      { key: 'B', text: 'Hình chữ nhật' },
      { key: 'C', text: 'Hình thoi' },
      { key: 'D', text: 'Hình bình hành' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định nghĩa: Hình chóp tứ giác đều có đáy là hình vuông và các cạnh bên bằng nhau.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết đặc điểm đáy của hình chóp tứ giác đều.',
    topicKeywords: ['hình chóp tứ giác đều', 'hình vuông', 'đáy'],
    chapter: 'Hình học',
    lesson: 'Hình chóp tứ giác đều',
  },
  {
    prompt: 'Hai tam giác đồng dạng với nhau theo tỉ số $k$ thì tỉ số chu vi của hai tam giác đó bằng:',
    options: [
      { key: 'A', text: '$k$' },
      { key: 'B', text: '$k^2$' },
      { key: 'C', text: '$\\sqrt{k}$' },
      { key: 'D', text: '$2k$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tính chất: Tỉ số chu vi của hai tam giác đồng dạng bằng đúng tỉ số đồng dạng $k$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết tính chất chu vi của hai tam giác đồng dạng.',
    topicKeywords: ['tam giác đồng dạng', 'tỉ số chu vi', 'tỉ số đồng dạng'],
    chapter: 'Hình học',
    lesson: 'Tam giác đồng dạng',
  },

  // --- THÔNG HIỂU (8 câu) ---
  {
    prompt: 'Cho hình bình hành $ABCD$ có $\\widehat{A} = 70^\\circ$. Số đo của góc $\\widehat{B}$ là:',
    options: [
      { key: 'A', text: '$110^\\circ$' },
      { key: 'B', text: '$70^\\circ$' },
      { key: 'C', text: '$120^\\circ$' },
      { key: 'D', text: '$90^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trong hình bình hành, hai góc kề một cạnh bù nhau: $\\widehat{B} = 180^\\circ - 70^\\circ = 110^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính số đo góc trong hình bình hành.',
    topicKeywords: ['hình bình hành', 'tính số đo góc', 'góc kề bù'],
    chapter: 'Hình học',
    lesson: 'Hình bình hành',
  },
  {
    prompt: 'Cho hình thoi có độ dài hai đường chéo là $8\\text{ cm}$ và $6\\text{ cm}$. Diện tích của hình thoi đó là:',
    options: [
      { key: 'A', text: '$24\\text{ cm}^2$' },
      { key: 'B', text: '$48\\text{ cm}^2$' },
      { key: 'C', text: '$14\\text{ cm}^2$' },
      { key: 'D', text: '$12\\text{ cm}^2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Diện tích hình thoi bằng nửa tích hai đường chéo: $S = \\frac{1}{2} d_1 d_2 = \\frac{1}{2} \\cdot 8 \\cdot 6 = 24\\text{ cm}^2$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính diện tích hình thoi từ độ dài hai đường chéo.',
    topicKeywords: ['hình thoi', 'diện tích', 'đường chéo'],
    chapter: 'Hình học',
    lesson: 'Hình thoi',
  },
  {
    prompt: 'Cho tam giác $ABC$ vuông tại $A$ có $AB = 6\\text{ cm}, AC = 8\\text{ cm}$. Độ dài cạnh huyền $BC$ là:',
    options: [
      { key: 'A', text: '$10\\text{ cm}$' },
      { key: 'B', text: '$14\\text{ cm}$' },
      { key: 'C', text: '$12\\text{ cm}$' },
      { key: 'D', text: '$\\sqrt{28}\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Áp dụng định lý Pythagore: $BC = \\sqrt{AB^2 + AC^2} = \\sqrt{6^2 + 8^2} = \\sqrt{100} = 10\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính cạnh huyền bằng định lý Pythagore.',
    topicKeywords: ['định lý pythagore', 'tam giác vuông', 'cạnh huyền'],
    chapter: 'Hình học',
    lesson: 'Định lý Pythagore',
  },
  {
    prompt: 'Một hình chóp tam giác đều có diện tích đáy bằng $18\\text{ cm}^2$ và chiều cao bằng $5\\text{ cm}$. Thể tích của hình chóp đó là:',
    options: [
      { key: 'A', text: '$30\\text{ cm}^3$' },
      { key: 'B', text: '$90\\text{ cm}^3$' },
      { key: 'C', text: '$45\\text{ cm}^3$' },
      { key: 'D', text: '$60\\text{ cm}^3$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Thể tích hình chóp: $V = \\frac{1}{3} S_{\\text{đáy}} \\cdot h = \\frac{1}{3} \\cdot 18 \\cdot 5 = 30\\text{ cm}^3$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính thể tích hình chóp tam giác đều.',
    topicKeywords: ['hình chóp tam giác đều', 'thể tích', 'chiều cao'],
    chapter: 'Hình học',
    lesson: 'Hình chóp tam giác đều',
  },
  {
    prompt: 'Một hình chóp tứ giác đều có cạnh đáy bằng $6\\text{ cm}$ và chiều cao bằng $4\\text{ cm}$. Thể tích khối chóp là:',
    options: [
      { key: 'A', text: '$48\\text{ cm}^3$' },
      { key: 'B', text: '$144\\text{ cm}^3$' },
      { key: 'C', text: '$72\\text{ cm}^3$' },
      { key: 'D', text: '$24\\text{ cm}^3$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Diện tích đáy là $S = 6^2 = 36\\text{ cm}^2$. Thể tích $V = \\frac{1}{3} S \\cdot h = \\frac{1}{3} \\cdot 36 \\cdot 4 = 48\\text{ cm}^3$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính thể tích hình chóp tứ giác đều.',
    topicKeywords: ['hình chóp tứ giác đều', 'thể tích', 'hình vuông'],
    chapter: 'Hình học',
    lesson: 'Hình chóp tứ giác đều',
  },
  {
    prompt: 'Cho tam giác $ABC$, đường thẳng $MN // BC$ ($M \\in AB, N \\in AC$). Biết $AM = 3\\text{ cm}, MB = 6\\text{ cm}, AN = 4\\text{ cm}$. Độ dài đoạn thẳng $NC$ là:',
    options: [
      { key: 'A', text: '$8\\text{ cm}$' },
      { key: 'B', text: '$6\\text{ cm}$' },
      { key: 'C', text: '$5\\text{ cm}$' },
      { key: 'D', text: '$7\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Theo định lý Thalès: $\\frac{AM}{MB} = \\frac{AN}{NC} \\Leftrightarrow \\frac{3}{6} = \\frac{4}{NC} \\Rightarrow NC = \\frac{6 \\cdot 4}{3} = 8\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính độ dài đoạn thẳng bằng định lý Thalès.',
    topicKeywords: ['định lý thalès', 'tỉ lệ đoạn thẳng', 'tam giác'],
    chapter: 'Hình học',
    lesson: 'Định lý Thalès trong tam giác',
  },
  {
    prompt: 'Hai tam giác đồng dạng $\\Delta A\'B\'C\' \\backsim \\Delta ABC$ theo tỉ số $k = 2$. Biết diện tích $\\Delta ABC = 15\\text{ cm}^2$. Diện tích tam giác $\\Delta A\'B\'C\'$ là:',
    options: [
      { key: 'A', text: '$60\\text{ cm}^2$' },
      { key: 'B', text: '$30\\text{ cm}^2$' },
      { key: 'C', text: '$45\\text{ cm}^2$' },
      { key: 'D', text: '$20\\text{ cm}^2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tỉ số diện tích của hai tam giác đồng dạng bằng bình phương tỉ số đồng dạng: $S_{A\'B\'C\'} = k^2 \\cdot S_{ABC} = 2^2 \\cdot 15 = 60\\text{ cm}^2$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính diện tích tam giác đồng dạng theo tỉ số k.',
    topicKeywords: ['tam giác đồng dạng', 'tỉ số diện tích', 'k bình phương'],
    chapter: 'Hình học',
    lesson: 'Tam giác đồng dạng',
  },

  // --- VẬN DỤNG (5 câu) ---
  {
    prompt: 'Để đo chiều cao một cột cờ, bạn An đo được bóng của cột cờ trên sân trường dài $6\\text{ m}$. Cùng thời điểm đó, một chiếc cọc cao $1{,}5\\text{ m}$ cắm vuông góc với mặt đất có bóng dài $1\\text{ m}$. Chiều cao của cột cờ là:',
    options: [
      { key: 'A', text: '$9\\text{ m}$' },
      { key: 'B', text: '$8\\text{ m}$' },
      { key: 'C', text: '$7{,}5\\text{ m}$' },
      { key: 'D', text: '$10\\text{ m}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Do các tia nắng song song nên hai tam giác tạo bởi vật và bóng đồng dạng: $\\frac{h}{6} = \\frac{1{,}5}{1} \\Rightarrow h = 6 \\times 1{,}5 = 9\\text{ m}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Vận dụng tam giác đồng dạng để đo chiều cao gián tiếp.',
    topicKeywords: ['ứng dụng thực tế', 'bóng cột cờ', 'tam giác đồng dạng'],
    chapter: 'Hình học',
    lesson: 'Ứng dụng thực tế của tam giác đồng dạng',
  },
  {
    prompt: 'Một chiếc lều cắm trại có dạng hình chóp tứ giác đều với cạnh đáy dài $2\\text{ m}$ và chiều cao bằng $1{,}8\\text{ m}$. Thể tích không gian bên trong lều là:',
    options: [
      { key: 'A', text: '$2{,}4\\text{ m}^3$' },
      { key: 'B', text: '$7{,}2\\text{ m}^3$' },
      { key: 'C', text: '$3{,}6\\text{ m}^3$' },
      { key: 'D', text: '$1{,}8\\text{ m}^3$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Thể tích lều: $V = \\frac{1}{3} S_{\\text{đáy}} \\cdot h = \\frac{1}{3} \\cdot 2^2 \\cdot 1{,}8 = \\frac{1}{3} \\cdot 4 \\cdot 1{,}8 = 2{,}4\\text{ m}^3$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Tính thể tích khối chóp tứ giác đều trong thực tế.',
    topicKeywords: ['ứng dụng thực tế', 'hình chóp tứ giác đều', 'lều cắm trại'],
    chapter: 'Hình học',
    lesson: 'Hình chóp tứ giác đều',
  },
  {
    prompt: 'Một mảnh vườn hình chữ nhật có chiều dài $20\\text{ m}$ và chiều rộng $15\\text{ m}$. Độ dài đường chéo nối hai đỉnh đối diện của mảnh vườn bằng:',
    options: [
      { key: 'A', text: '$25\\text{ m}$' },
      { key: 'B', text: '$35\\text{ m}$' },
      { key: 'C', text: '$30\\text{ m}$' },
      { key: 'D', text: '$22\\text{ m}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Đường chéo hình chữ nhật $d = \\sqrt{20^2 + 15^2} = \\sqrt{400 + 225} = \\sqrt{625} = 25\\text{ m}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Áp dụng định lý Pythagore tính đường chéo hình chữ nhật thực tế.',
    topicKeywords: ['đường chéo', 'hình chữ nhật', 'pythagore thực tế'],
    chapter: 'Hình học',
    lesson: 'Hình chữ nhật',
  },
  {
    prompt: 'Một hình thoi có chu vi bằng $20\\text{ cm}$ và một đường chéo dài $6\\text{ cm}$. Độ dài đường chéo còn lại là:',
    options: [
      { key: 'A', text: '$8\\text{ cm}$' },
      { key: 'B', text: '$4\\text{ cm}$' },
      { key: 'C', text: '$10\\text{ cm}$' },
      { key: 'D', text: '$7\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Cạnh hình thoi $a = 20 / 4 = 5\\text{ cm}$. Nửa đường chéo đã biết là $3\\text{ cm}$. Nửa đường chéo còn lại: $\\sqrt{5^2 - 3^2} = 4\\text{ cm} \\Rightarrow$ Đường chéo còn lại là $8\\text{ cm}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Vận dụng tính chất hình thoi và Pythagore tính đường chéo.',
    topicKeywords: ['hình thoi', 'đường chéo', 'pythagore'],
    chapter: 'Hình học',
    lesson: 'Hình thoi',
  },
];

// ============================================================================
// HÌNH HỌC KHỐI 7 (Góc đối đỉnh, Kề bù, Song song, Tam giác bằng nhau, Ba đường đồng quy)
// ============================================================================
export const GRADE_7_GEOMETRY_QUESTIONS: ConcreteGeometryQuestion[] = [
  // --- NHẬN BIẾT (9 câu) ---
  {
    prompt: 'Hai góc đối đỉnh thì:',
    options: [
      { key: 'A', text: 'Bằng nhau' },
      { key: 'B', text: 'Có tổng số đo bằng $180^\\circ$' },
      { key: 'C', text: 'Có tổng số đo bằng $90^\\circ$' },
      { key: 'D', text: 'Kề nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định lý: Hai góc đối đỉnh thì bằng nhau.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết tính chất của hai góc đối đỉnh.',
    topicKeywords: ['góc đối đỉnh', 'bằng nhau', 'góc'],
    chapter: 'Hình học',
    lesson: 'Góc ở vị trí đặc biệt',
  },
  {
    prompt: 'Hai góc kề bù là hai góc vừa kề nhau vừa bù nhau, tổng số đo của chúng luôn bằng:',
    options: [
      { key: 'A', text: '$180^\\circ$' },
      { key: 'B', text: '$90^\\circ$' },
      { key: 'C', text: '$360^\\circ$' },
      { key: 'D', text: '$45^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Hai góc kề bù có tổng số đo bằng $180^\\circ$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định nghĩa và tính chất của hai góc kề bù.',
    topicKeywords: ['kề bù', '180 độ', 'góc'],
    chapter: 'Hình học',
    lesson: 'Góc ở vị trí đặc biệt',
  },
  {
    prompt: 'Tổng số đo ba góc trong một tam giác luôn bằng:',
    options: [
      { key: 'A', text: '$180^\\circ$' },
      { key: 'B', text: '$360^\\circ$' },
      { key: 'C', text: '$90^\\circ$' },
      { key: 'D', text: '$270^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định lý: Tổng ba góc trong bất kỳ tam giác nào luôn bằng $180^\\circ$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định lý tổng ba góc trong một tam giác.',
    topicKeywords: ['tổng ba góc', 'tam giác', '180 độ'],
    chapter: 'Hình học',
    lesson: 'Định lý tổng ba góc của tam giác',
  },
  {
    prompt: 'Nếu một đường thẳng cắt hai đường thẳng song song thì:',
    options: [
      { key: 'A', text: 'Hai góc so le trong bằng nhau' },
      { key: 'B', text: 'Hai góc đồng vị bù nhau' },
      { key: 'C', text: 'Hai góc trong cùng phía bằng nhau' },
      { key: 'D', text: 'Tất cả các góc đều bằng nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tính chất hai đường thẳng song song: Hai góc so le trong bằng nhau, hai góc đồng vị bằng nhau.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết tính chất của hai đường thẳng song song.',
    topicKeywords: ['hai đường thẳng song song', 'so le trong', 'đồng vị'],
    chapter: 'Hình học',
    lesson: 'Hai đường thẳng song song',
  },
  {
    prompt: 'Tam giác đều là tam giác có:',
    options: [
      { key: 'A', text: 'Ba cạnh bằng nhau và mỗi góc bằng $60^\\circ$' },
      { key: 'B', text: 'Hai cạnh bằng nhau và một góc vuông' },
      { key: 'C', text: 'Ba cạnh khác nhau đôi một' },
      { key: 'D', text: 'Một góc tù và hai cạnh bằng nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định nghĩa: Tam giác đều có 3 cạnh bằng nhau và 3 góc bằng nhau, mỗi góc bằng $60^\\circ$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định nghĩa và tính chất của tam giác đều.',
    topicKeywords: ['tam giác đều', 'ba cạnh bằng nhau', '60 độ'],
    chapter: 'Hình học',
    lesson: 'Tam giác cân',
  },
  {
    prompt: 'Giao điểm của ba đường trung tuyến trong một tam giác được gọi là:',
    options: [
      { key: 'A', text: 'Trọng tâm của tam giác' },
      { key: 'B', text: 'Trực tâm của tam giác' },
      { key: 'C', text: 'Tâm đường tròn ngoại tiếp' },
      { key: 'D', text: 'Tâm đường tròn nội tiếp' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Khái niệm: Giao điểm của ba đường trung tuyến trong tam giác gọi là trọng tâm.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết khái niệm trọng tâm trong tam giác.',
    topicKeywords: ['đường trung tuyến', 'trọng tâm', 'đồng quy'],
    chapter: 'Hình học',
    lesson: 'Đường trung tuyến của tam giác',
  },
  {
    prompt: 'Giao điểm của ba đường cao trong một tam giác được gọi là:',
    options: [
      { key: 'A', text: 'Trực tâm của tam giác' },
      { key: 'B', text: 'Trọng tâm của tam giác' },
      { key: 'C', text: 'Điểm cách đều ba cạnh' },
      { key: 'D', text: 'Tâm đường tròn' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Khái niệm: Ba đường cao của tam giác cùng đi qua một điểm, điểm đó gọi là trực tâm của tam giác.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết khái niệm trực tâm của tam giác.',
    topicKeywords: ['đường cao', 'trực tâm', 'tam giác'],
    chapter: 'Hình học',
    lesson: 'Đường cao của tam giác',
  },

  // --- THÔNG HIỂU (8 câu) ---
  {
    prompt: 'Cho góc $\\widehat{xOy} = 70^\\circ$. Tia $Oz$ là tia phân giác của góc $\\widehat{xOy}$. Số đo của góc $\\widehat{xOz}$ là:',
    options: [
      { key: 'A', text: '$35^\\circ$' },
      { key: 'B', text: '$70^\\circ$' },
      { key: 'C', text: '$140^\\circ$' },
      { key: 'D', text: '$45^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tia phân giác chia góc thành hai phần bằng nhau: $\\widehat{xOz} = \\frac{70^\\circ}{2} = 35^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính số đo góc tạo bởi tia phân giác.',
    topicKeywords: ['tia phân giác', 'số đo góc', 'chia đôi'],
    chapter: 'Hình học',
    lesson: 'Tia phân giác của một góc',
  },
  {
    prompt: 'Cho hai góc kề bù $\\widehat{AOB}$ và $\\widehat{BOC}$, biết $\\widehat{AOB} = 55^\\circ$. Số đo của góc $\\widehat{BOC}$ bằng:',
    options: [
      { key: 'A', text: '$125^\\circ$' },
      { key: 'B', text: '$35^\\circ$' },
      { key: 'C', text: '$135^\\circ$' },
      { key: 'D', text: '$145^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Hai góc kề bù có tổng bằng $180^\\circ \\Rightarrow \\widehat{BOC} = 180^\\circ - 55^\\circ = 125^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính số đo góc kề bù.',
    topicKeywords: ['kề bù', 'tính số đo góc', '180 độ'],
    chapter: 'Hình học',
    lesson: 'Góc ở vị trí đặc biệt',
  },
  {
    prompt: 'Cho tam giác $ABC$ có $\\widehat{A} = 50^\\circ, \\widehat{B} = 70^\\circ$. Số đo của góc $\\widehat{C}$ là:',
    options: [
      { key: 'A', text: '$60^\\circ$' },
      { key: 'B', text: '$80^\\circ$' },
      { key: 'C', text: '$50^\\circ$' },
      { key: 'D', text: '$70^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tổng ba góc bằng $180^\\circ \\Rightarrow \\widehat{C} = 180^\\circ - (50^\\circ + 70^\\circ) = 60^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính số đo góc thứ ba trong tam giác.',
    topicKeywords: ['tổng ba góc', 'tam giác', 'tìm góc'],
    chapter: 'Hình học',
    lesson: 'Định lý tổng ba góc của tam giác',
  },
  {
    prompt: 'Cho tam giác $ABC$ cân tại $A$ có $\\widehat{A} = 40^\\circ$. Số đo của góc ở đáy $\\widehat{B}$ là:',
    options: [
      { key: 'A', text: '$70^\\circ$' },
      { key: 'B', text: '$40^\\circ$' },
      { key: 'C', text: '$80^\\circ$' },
      { key: 'D', text: '$60^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trong tam giác cân tại $A$: $\\widehat{B} = \\widehat{C} = \\frac{180^\\circ - 40^\\circ}{2} = 70^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính số đo góc ở đáy của tam giác cân.',
    topicKeywords: ['tam giác cân', 'góc ở đáy', 'tính góc'],
    chapter: 'Hình học',
    lesson: 'Tam giác cân',
  },
  {
    prompt: 'Cho $\\Delta ABC = \\Delta DEF$. Biết $AB = 5\\text{ cm}, \\widehat{C} = 45^\\circ$. Khẳng định nào sau đây là ĐÚNG?',
    options: [
      { key: 'A', text: '$DE = 5\\text{ cm}$ và $\\widehat{F} = 45^\\circ$' },
      { key: 'B', text: '$DF = 5\\text{ cm}$ và $\\widehat{D} = 45^\\circ$' },
      { key: 'C', text: '$EF = 5\\text{ cm}$ và $\\widehat{E} = 45^\\circ$' },
      { key: 'D', text: '$DE = 5\\text{ cm}$ và $\\widehat{D} = 45^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Khi hai tam giác bằng nhau, các cặp cạnh và góc tương ứng bằng nhau: $DE = AB = 5\\text{ cm}$ và $\\widehat{F} = \\widehat{C} = 45^\\circ$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Xác định các yếu tố tương ứng của hai tam giác bằng nhau.',
    topicKeywords: ['hai tam giác bằng nhau', 'cạnh tương ứng', 'góc tương ứng'],
    chapter: 'Hình học',
    lesson: 'Các trường hợp bằng nhau của tam giác',
  },
  {
    prompt: 'Cho tam giác vuông có hai cạnh góc vuông là $6\\text{ cm}$ và $8\\text{ cm}$. Độ dài cạnh huyền là:',
    options: [
      { key: 'A', text: '$10\\text{ cm}$' },
      { key: 'B', text: '$14\\text{ cm}$' },
      { key: 'C', text: '$12\\text{ cm}$' },
      { key: 'D', text: '$\\sqrt{28}\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định lý Pythagore: Cạnh huyền $c = \\sqrt{6^2 + 8^2} = \\sqrt{100} = 10\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính cạnh huyền tam giác vuông.',
    topicKeywords: ['pythagore', 'cạnh huyền', 'tam giác vuông'],
    chapter: 'Hình học',
    lesson: 'Định lý Pythagore',
  },

  // --- VẬN DỤNG (5 câu) ---
  {
    prompt: 'Cho tam giác $ABC$ có trọng tâm $G$, đường trung tuyến $AM = 9\\text{ cm}$. Độ dài đoạn thẳng $AG$ bằng:',
    options: [
      { key: 'A', text: '$6\\text{ cm}$' },
      { key: 'B', text: '$3\\text{ cm}$' },
      { key: 'C', text: '$4{,}5\\text{ cm}$' },
      { key: 'D', text: '$7\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Trọng tâm cách đỉnh một khoảng bằng $\\frac{2}{3}$ độ dài đường trung tuyến: $AG = \\frac{2}{3} AM = \\frac{2}{3} \\cdot 9 = 6\\text{ cm}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Vận dụng tính chất trọng tâm của tam giác.',
    topicKeywords: ['trọng tâm', 'đường trung tuyến', 'tỉ số 2/3'],
    chapter: 'Hình học',
    lesson: 'Đường trung tuyến của tam giác',
  },
  {
    prompt: 'Cho tam giác $ABC$ có $\\widehat{A} = 80^\\circ$, góc ngoài tại đỉnh $C$ có số đo bằng $130^\\circ$. Số đo của góc $\\widehat{B}$ là:',
    options: [
      { key: 'A', text: '$50^\\circ$' },
      { key: 'B', text: '$60^\\circ$' },
      { key: 'C', text: '$70^\\circ$' },
      { key: 'D', text: '$80^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Góc ngoài của tam giác bằng tổng hai góc trong không kề với nó: $\\widehat{C}_{\\text{ngoài}} = \\widehat{A} + \\widehat{B} \\Rightarrow 130^\\circ = 80^\\circ + \\widehat{B} \\Rightarrow \\widehat{B} = 50^\\circ$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Vận dụng tính chất góc ngoài của tam giác.',
    topicKeywords: ['góc ngoài', 'tổng góc trong', 'tam giác'],
    chapter: 'Hình học',
    lesson: 'Định lý tổng ba góc của tam giác',
  },
  {
    prompt: 'Bộ ba đoạn thẳng có độ dài nào sau đây CÓ THỂ là độ dài ba cạnh của một tam giác?',
    options: [
      { key: 'A', text: '$3\\text{ cm}, 4\\text{ cm}, 5\\text{ cm}$' },
      { key: 'B', text: '$2\\text{ cm}, 3\\text{ cm}, 5\\text{ cm}$' },
      { key: 'C', text: '$1\\text{ cm}, 2\\text{ cm}, 4\\text{ cm}$' },
      { key: 'D', text: '$3\\text{ cm}, 6\\text{ cm}, 10\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Theo bất đẳng thức tam giác, tổng hai cạnh bất kỳ phải lớn hơn cạnh còn lại: $3 + 4 = 7 > 5$ thỏa mãn.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Vận dụng bất đẳng thức tam giác để kiểm tra tính tạo thành tam giác.',
    topicKeywords: ['bất đẳng thức tam giác', 'ba cạnh', 'độ dài'],
    chapter: 'Hình học',
    lesson: 'Bất đẳng thức tam giác',
  },
  {
    prompt: 'Một cái cây bị bão quật gãy ngang thân, ngọn cây chạm đất cách gốc $3\\text{ m}$. Điểm gãy cách gốc $4\\text{ m}$. Chiều cao ban đầu của cây (trước khi bị gãy) là:',
    options: [
      { key: 'A', text: '$9\\text{ m}$' },
      { key: 'B', text: '$7\\text{ m}$' },
      { key: 'C', text: '$8\\text{ m}$' },
      { key: 'D', text: '$12\\text{ m}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Đoạn ngọn bị gãy là cạnh huyền: $c = \\sqrt{3^2 + 4^2} = 5\\text{ m}$. Chiều cao ban đầu của cây là $4 + 5 = 9\\text{ m}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Ứng dụng định lý Pythagore vào bài toán cây gãy thực tế.',
    topicKeywords: ['ứng dụng thực tế', 'cây gãy', 'pythagore'],
    chapter: 'Hình học',
    lesson: 'Định lý Pythagore',
  },
];

// ============================================================================
// HÌNH HỌC KHỐI 6 (Tam giác đều, Hình vuông, Lục giác đều, Hình chữ nhật, Hình thoi, Hình bình hành, Điểm, Đoạn thẳng, Góc)
// ============================================================================
export const GRADE_6_GEOMETRY_QUESTIONS: ConcreteGeometryQuestion[] = [
  // --- NHẬN BIẾT (9 câu) ---
  {
    prompt: 'Tam giác đều có các đặc điểm nào sau đây?',
    options: [
      { key: 'A', text: 'Ba cạnh bằng nhau và ba góc bằng nhau' },
      { key: 'B', text: 'Hai cạnh bằng nhau và một góc vuông' },
      { key: 'C', text: 'Ba cạnh bằng nhau và ba góc không bằng nhau' },
      { key: 'D', text: 'Có hai đường chéo bằng nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định nghĩa: Tam giác đều là tam giác có 3 cạnh bằng nhau và 3 góc bằng nhau (mỗi góc bằng $60^\\circ$).',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết đặc điểm của tam giác đều.',
    topicKeywords: ['tam giác đều', 'ba cạnh bằng nhau', 'góc 60 độ'],
    chapter: 'Hình học',
    lesson: 'Tam giác đều, hình vuông, lục giác đều',
  },
  {
    prompt: 'Hình lục giác đều có bao nhiêu đường chéo chính?',
    options: [
      { key: 'A', text: '$3$' },
      { key: 'B', text: '$6$' },
      { key: 'C', text: '$4$' },
      { key: 'D', text: '$2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Hình lục giác đều có 3 đường chéo chính nối các đỉnh đối diện và bằng nhau.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết số đường chéo chính của hình lục giác đều.',
    topicKeywords: ['lục giác đều', 'đường chéo chính', 'hình học trực quan'],
    chapter: 'Hình học',
    lesson: 'Tam giác đều, hình vuông, lục giác đều',
  },
  {
    prompt: 'Khẳng định nào sau đây là ĐÚNG về hình thoi?',
    options: [
      { key: 'A', text: 'Bốn cạnh bằng nhau và hai đường chéo vuông góc với nhau' },
      { key: 'B', text: 'Bốn góc bằng nhau và bằng $90^\\circ$' },
      { key: 'C', text: 'Hai đường chéo bằng nhau' },
      { key: 'D', text: 'Chỉ có hai cạnh đối bằng nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Hình thoi có 4 cạnh bằng nhau và hai đường chéo vuông góc với nhau tại trung điểm của mỗi đường.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết đặc điểm và tính chất của hình thoi.',
    topicKeywords: ['hình thoi', 'bốn cạnh bằng nhau', 'đường chéo vuông góc'],
    chapter: 'Hình học',
    lesson: 'Hình thoi, hình chữ nhật, hình bình hành',
  },
  {
    prompt: 'Hình thang cân có hai cạnh bên như thế nào?',
    options: [
      { key: 'A', text: 'Bằng nhau' },
      { key: 'B', text: 'Song song' },
      { key: 'C', text: 'Vuông góc' },
      { key: 'D', text: 'Trùng nhau' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Tính chất hình thang cân: Hai cạnh bên bằng nhau và hai đường chéo bằng nhau.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết tính chất cạnh bên của hình thang cân.',
    topicKeywords: ['hình thang cân', 'hai cạnh bên bằng nhau'],
    chapter: 'Hình học',
    lesson: 'Hình thang cân',
  },
  {
    prompt: 'Điểm $M$ là trung điểm của đoạn thẳng $AB$ khi:',
    options: [
      { key: 'A', text: '$M$ nằm giữa $A, B$ và $MA = MB$' },
      { key: 'B', text: '$MA = MB$' },
      { key: 'C', text: '$M$ nằm giữa $A$ và $B$' },
      { key: 'D', text: '$MA + MB = 2AB$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Định nghĩa: Điểm $M$ nằm giữa $A, B$ và cách đều hai đầu mút ($MA = MB$) thì $M$ là trung điểm của $AB$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết định nghĩa trung điểm của đoạn thẳng.',
    topicKeywords: ['trung điểm', 'đoạn thẳng', 'điểm nằm giữa'],
    chapter: 'Hình học',
    lesson: 'Đoạn thẳng và độ dài đoạn thẳng',
  },
  {
    prompt: 'Góc vuông là góc có số đo bằng:',
    options: [
      { key: 'A', text: '$90^\\circ$' },
      { key: 'B', text: '$180^\\circ$' },
      { key: 'C', text: '$60^\\circ$' },
      { key: 'D', text: '$45^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Góc vuông có số đo bằng $90^\\circ$, góc bẹt bằng $180^\\circ$.',
    cognitiveLevel: 'nhanBiet',
    learningObjective: 'Nhận biết số đo góc vuông.',
    topicKeywords: ['góc vuông', '90 độ', 'góc'],
    chapter: 'Hình học',
    lesson: 'Góc và số đo góc',
  },

  // --- THÔNG HIỂU (8 câu) ---
  {
    prompt: 'Cho đoạn thẳng $AB = 10\\text{ cm}$. Điểm $M$ là trung điểm của đoạn thẳng $AB$. Độ dài của đoạn thẳng $AM$ là:',
    options: [
      { key: 'A', text: '$5\\text{ cm}$' },
      { key: 'B', text: '$10\\text{ cm}$' },
      { key: 'C', text: '$20\\text{ cm}$' },
      { key: 'D', text: '$2{,}5\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Vì $M$ là trung điểm của $AB$ nên $AM = \\frac{AB}{2} = \\frac{10}{2} = 5\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính độ dài đoạn thẳng dựa vào trung điểm.',
    topicKeywords: ['trung điểm', 'tính độ dài', 'đoạn thẳng'],
    chapter: 'Hình học',
    lesson: 'Đoạn thẳng và độ dài đoạn thẳng',
  },
  {
    prompt: 'Chu vi của một hình vuông có cạnh dài $7\\text{ cm}$ là:',
    options: [
      { key: 'A', text: '$28\\text{ cm}$' },
      { key: 'B', text: '$49\\text{ cm}^2$' },
      { key: 'C', text: '$14\\text{ cm}$' },
      { key: 'D', text: '$21\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Chu vi hình vuông: $C = 4 \\times a = 4 \\times 7 = 28\\text{ cm}$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính chu vi của hình vuông.',
    topicKeywords: ['hình vuông', 'chu vi', 'cạnh'],
    chapter: 'Hình học',
    lesson: 'Tam giác đều, hình vuông, lục giác đều',
  },
  {
    prompt: 'Một hình chữ nhật có chiều dài $8\\text{ cm}$ và chiều rộng $5\\text{ cm}$. Diện tích của hình chữ nhật đó là:',
    options: [
      { key: 'A', text: '$40\\text{ cm}^2$' },
      { key: 'B', text: '$26\\text{ cm}$' },
      { key: 'C', text: '$13\\text{ cm}^2$' },
      { key: 'D', text: '$80\\text{ cm}^2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Diện tích hình chữ nhật: $S = a \\times b = 8 \\times 5 = 40\\text{ cm}^2$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính diện tích hình chữ nhật.',
    topicKeywords: ['hình chữ nhật', 'diện tích', 'chiều dài chiều rộng'],
    chapter: 'Hình học',
    lesson: 'Chu vi và diện tích các hình tứ giác',
  },
  {
    prompt: 'Diện tích của một hình thoi có độ dài hai đường chéo lần lượt là $8\\text{ cm}$ và $6\\text{ cm}$ bằng:',
    options: [
      { key: 'A', text: '$24\\text{ cm}^2$' },
      { key: 'B', text: '$48\\text{ cm}^2$' },
      { key: 'C', text: '$14\\text{ cm}^2$' },
      { key: 'D', text: '$28\\text{ cm}^2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Diện tích hình thoi: $S = \\frac{1}{2} \\times d_1 \\times d_2 = \\frac{1}{2} \\times 8 \\times 6 = 24\\text{ cm}^2$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính diện tích hình thoi bằng hai đường chéo.',
    topicKeywords: ['hình thoi', 'diện tích', 'đường chéo'],
    chapter: 'Hình học',
    lesson: 'Chu vi và diện tích các hình tứ giác',
  },
  {
    prompt: 'Một hình bình hành có độ dài đáy là $12\\text{ cm}$ và chiều cao tương ứng là $5\\text{ cm}$. Diện tích của hình bình hành đó là:',
    options: [
      { key: 'A', text: '$60\\text{ cm}^2$' },
      { key: 'B', text: '$30\\text{ cm}^2$' },
      { key: 'C', text: '$34\\text{ cm}$' },
      { key: 'D', text: '$17\\text{ cm}^2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Diện tích hình bình hành: $S = a \\times h = 12 \\times 5 = 60\\text{ cm}^2$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính diện tích hình bình hành.',
    topicKeywords: ['hình bình hành', 'diện tích', 'đáy chiều cao'],
    chapter: 'Hình học',
    lesson: 'Chu vi và diện tích các hình tứ giác',
  },
  {
    prompt: 'Hình thang cân có độ dài hai đáy lần lượt là $6\\text{ cm}$ và $10\\text{ cm}$, chiều cao bằng $4\\text{ cm}$. Diện tích của hình thang cân là:',
    options: [
      { key: 'A', text: '$32\\text{ cm}^2$' },
      { key: 'B', text: '$64\\text{ cm}^2$' },
      { key: 'C', text: '$16\\text{ cm}^2$' },
      { key: 'D', text: '$40\\text{ cm}^2$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Diện tích hình thang: $S = \\frac{(a + b) \\times h}{2} = \\frac{(6 + 10) \\times 4}{2} = 32\\text{ cm}^2$.',
    cognitiveLevel: 'thongHieu',
    learningObjective: 'Tính diện tích hình thang cân.',
    topicKeywords: ['hình thang cân', 'diện tích hình thang', 'hai đáy'],
    chapter: 'Hình học',
    lesson: 'Chu vi và diện tích các hình tứ giác',
  },

  // --- VẬN DỤNG (5 câu) ---
  {
    prompt: 'Bác Năm có một mảnh vườn hình chữ nhật dài $15\\text{ m}$ và rộng $8\\text{ m}$. Bác muốn làm hàng rào bao quanh mảnh vườn nhưng để lại một lối đi rộng $2\\text{ m}$. Chiều dài hàng rào bác Năm cần làm là:',
    options: [
      { key: 'A', text: '$44\\text{ m}$' },
      { key: 'B', text: '$46\\text{ m}$' },
      { key: 'C', text: '$48\\text{ m}$' },
      { key: 'D', text: '$42\\text{ m}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Chu vi mảnh vườn là $(15 + 8) \\times 2 = 46\\text{ m}$. Trừ đi lối đi $2\\text{ m}$, chiều dài hàng rào là $46 - 2 = 44\\text{ m}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Ứng dụng chu vi hình chữ nhật vào bài toán làm hàng rào vườn.',
    topicKeywords: ['ứng dụng thực tế', 'hàng rào vườn', 'chu vi chữ nhật'],
    chapter: 'Hình học',
    lesson: 'Chu vi và diện tích các hình tứ giác',
  },
  {
    prompt: 'Một căn phòng hình chữ nhật có kích thước $6\\text{ m} \\times 4\\text{ m}$. Người ta dùng các viên gạch men hình vuông cạnh $40\\text{ cm}$ để lát nền. Số viên gạch cần dùng là (bỏ qua mép vữa):',
    options: [
      { key: 'A', text: '$150$ viên' },
      { key: 'B', text: '$120$ viên' },
      { key: 'C', text: '$200$ viên' },
      { key: 'D', text: '$100$ viên' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Diện tích nền: $6 \\times 4 = 24\\text{ m}^2 = 240\\,000\\text{ cm}^2$. Diện tích 1 viên gạch: $40 \\times 40 = 1\\,600\\text{ cm}^2$. Số viên gạch: $240\\,000 : 1\\,600 = 150$ viên.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Ứng dụng diện tích hình chữ nhật vào bài toán lát nền gạch.',
    topicKeywords: ['ứng dụng thực tế', 'lát gạch nền', 'diện tích'],
    chapter: 'Hình học',
    lesson: 'Chu vi và diện tích các hình tứ giác',
  },
  {
    prompt: 'Trên tia $Ox$, lấy hai điểm $A$ và $B$ sao cho $OA = 3\\text{ cm}, OB = 7\\text{ cm}$. Độ dài của đoạn thẳng $AB$ là:',
    options: [
      { key: 'A', text: '$4\\text{ cm}$' },
      { key: 'B', text: '$10\\text{ cm}$' },
      { key: 'C', text: '$3\\text{ cm}$' },
      { key: 'D', text: '$5\\text{ cm}$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Vì $OA < OB$ ($3 < 7$) nên điểm $A$ nằm giữa $O$ và $B$. Ta có $AB = OB - OA = 7 - 3 = 4\\text{ cm}$.',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Tính độ dài đoạn thẳng khi biết vị trí các điểm trên tia.',
    topicKeywords: ['tia', 'điểm nằm giữa', 'đoạn thẳng'],
    chapter: 'Hình học',
    lesson: 'Đoạn thẳng và độ dài đoạn thẳng',
  },
  {
    prompt: 'Lúc 3 giờ đúng, góc tạo bởi kim giờ và kim phút của chiếc đồng hồ treo tường có số đo bằng:',
    options: [
      { key: 'A', text: '$90^\\circ$' },
      { key: 'B', text: '$60^\\circ$' },
      { key: 'C', text: '$120^\\circ$' },
      { key: 'D', text: '$180^\\circ$' },
    ],
    correctOption: 'A',
    solutionExplanation: 'Mặt đồng hồ chia thành 12 khoảng bằng nhau, mỗi khoảng ứng với $30^\\circ$. Lúc 3 giờ, kim phút chỉ số 12 và kim giờ chỉ số 3, góc tạo thành là $3 \\times 30^\\circ = 90^\\circ$ (góc vuông).',
    cognitiveLevel: 'vanDung',
    learningObjective: 'Ứng dụng số đo góc vào bài toán xem giờ đồng hồ thực tế.',
    topicKeywords: ['ứng dụng thực tế', 'kim đồng hồ', 'góc vuông'],
    chapter: 'Hình học',
    lesson: 'Góc và số đo góc',
  },
];
